# Generated by Django 4.1.5 on 2023-01-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
